<?php
// api/src/Entity/UserEskap.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 *  An UserEskap
 * 
 * @ORM\Entity
 */
#[ApiResource]
class UserEskap
{
    /** The id of this user (autogenerated). 
     * 
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
    */
    private ?int $id = null;


    /** The userid of this User (coming from firebase). 
     * 
     * @ORM\Column(nullable=true)
    */
    public ?string $userid = null;

    /** The firstname of this User 
     * 
     *  @ORM\Column(nullable=true)
    */
    public ?string $firstname = null;

    /** The lastname of this User 
     * 
     * @ORM\Column(nullable=true)
    */
    public ?string $lastname = null;

    /** @var Integer[] id of eskap done by this User. 
     * 
     * @ORM\Column(type="array")
    */
    public iterable $donelist;

    /** @var Integer[] id of fav eskap of this User.  
     * 
     * @ORM\Column(type="array")
    */
    public iterable $favlist;

    public function __construct()
    {
        $this->donelist = new ArrayCollection();
        $this->favlist = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
}